# Generated by Django 5.0.3 on 2024-03-24 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='participant_count',
            field=models.IntegerField(default=0),
        ),
    ]
