# Generated by Django 5.0.3 on 2024-03-24 07:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_event_participant_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 24, 7, 3, 10, 926274, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
